name: CI
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:8.4-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: PHPUnit
        run: |
          apt update
          apt install -y libzip-dev unzip
          pecl install xdebug
          docker-php-ext-enable xdebug
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer install
          composer run test

      - name: Lint
        run: composer run lint

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

